using System;
using System.Collections.Generic;
using System.Linq;
using ProjectEulerDataContracts;

namespace ProjectEulerLib
{
    public class Problem101Solver : ProblemSolver
    {
        public Problem101Solver() : base()
        {
            Problem.Id = 101;
            Problem.UpperBound = 20;
            Problem.IsClosedOnRight = true;
            Problem.Title = "Optimum polynomial";
            Problem.Description = 
@"

If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function,
un = n3: 1, 8, 27, 64, 125, 216, ...

Suppose we were only given the first two terms of this sequence. Working on the principle that 'simple is best' we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define OP(k, n) to be the nth term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that OP(k, n) will accurately generate the terms of the sequence for n ≤ k, and potentially the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call it a bad OP (BOP).

As a basis, if we were only given the first term of sequence, it would be most sensible to assume constancy; that is, for n ≥ 2, OP(1, n) = u1.

Hence we obtain the following OPs for the cubic sequence:
OP(1, n) = 1 	1, 1, 1, 1, ...
OP(2, n) = 7n−6 	1, 8, 15, ...
OP(3, n) = 6n^2−11n+6      	1, 8, 27, 58, ...
OP(4, n) = n^3 	1, 8, 27, 64, 125, ...

Clearly no BOPs exist for k ≥ 4.

By considering the sum of FITs generated by the BOPs (indicated in red above), we obtain 1 + 15 + 58 = 74.

Consider the following tenth degree polynomial generating function:

un = 1 − n + n^2 − n^3 + n^4 − n^5 + n^6 − n^7 + n^8 − n^9 + n^10

Find the sum of FITs for the BOPs.
";

            Problem.Solutions.Add(new Solution
            {
                ProblemId = 101,
                Description = 
@"for op from 1 to 10
build a linear equation matrix
OP = 1: |1 = 1|
OP = 2: |1 1 =   1|
        |2 1 = 683|
OP = 3: |1 1 1 =   1|
        |4 2 1 = 683|
        |9 3 1 = xxx|
...
solve the linear equation matrix, use (OP + 1) in the equation, that the FIT for OP
sum up all the FITs
",
                Version = 1,
            });
            // Problem.Solutions.Add(new Solution
            // {
            //     ProblemId = 0,
            //     Description = "",
            //     Version = 2,
            // });
            // Problem.Solutions.Add(new Solution
            // {
            //     ProblemId = 0,
            //     Description = "",
            //     Version = 3,
            // });
        }

        public override string solution1()
        {
            double sum = 0;
            for(int op = 1; op <= 10; op ++)
            {
                double [][] content = new double[op][];

                for(int n = 1; n <= op; n ++)
                {
                    content[n - 1] = new double[op + 1];
                    for(int c = 0; c < op; c ++)
                    {
                        content[n - 1][c] = Math.Pow(n, op - c - 1);
                    }

                    content[n - 1][op] = 0;
                    for(int p = 0; p <= 10; p ++)
                    {
                        content[n - 1][op] += (p % 2 == 0 ? 1 : -1) * Math.Pow(n, p);
                    }
                }
                
                MoreMath.LinearEquationMatrix matrix = new MoreMath.LinearEquationMatrix(content);
                double[] opSoutions = matrix.SolveLinearEquations();
                double FIT = 0;
                for(int s = 0; s < opSoutions.Length; s ++)
                {
                    FIT += Math.Pow(op + 1, op - s - 1) * opSoutions[s];
                }
                sum += FIT;
            }

            return sum.ToString();

            // return "working on it;";
        }

        public override string solution2()
        {
            return "";
        }

        public override string solution3()
        {
            return "";
        }
    }
}
